services:
  meshcore-ai:
    image: meshcore-ai:latest
    container_name: meshcore-ai
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${HTTP_PORT:-8080}:${HTTP_PORT:-8080}"
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    group_add:
      - 20 # "dialout" (stat -c "%g" /dev/ttyUSB0)
    volumes:
      - ./src/data:/app/src/data
