services:
  meshcore-ai:
    image: meshcore-ai:latest
    container_name: meshcore-ai
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    group_add:
      - 20 # "dialout" (stat -c "%g" /dev/ttyUSB0)